
CONFIG_SYS_CLOCK_EXISTS=y
CONFIG_DEBUG=y
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

######  OLED #####
#SSD1306

#enable I2c
CONFIG_I2C=y

#enable SSD1306 display
CONFIG_SSD1306=y

#enable display subsystem
CONFIG_DISPLAY=y

#cfb 字符帧缓冲(提供 cfb_* API)
CONFIG_CHARACTER_FRAMEBUFFER=y

# 禁用内置默认字体，只用自己的
CONFIG_CHARACTER_FRAMEBUFFER_USE_DEFAULT_FONTS=n

#cfb 内部用 k_malloc 分配帧缓冲，需要内核堆
CONFIG_HEAP_MEM_POOL_SIZE=2048


#MPU6050
CONFIG_SENSOR=y
CONFIG_MPU6050=y

#如果使用lvgl
#CONFIG_LVGL=y

#按键 Input Subsystem(可选)

CONFIG_INPUT=y
CONFIG_INPUT_GPIO_KEYS=y

#shell(i2c scan调试)
# CONFIG_SHELL=y
# CONFIG_I2C_SHELL=y


#串口
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y      #中断驱动
CONFIG_DMA=y                        #开启DMA
CONFIG_DMA_STM32=y
CONFIG_RING_BUFFER=y                #环形缓冲区 (IT 模式 TX)
CONFIG_UART_INTERRUPT_DRIVEN=y      #uart_it 开启
CONFIG_UART_ASYNC_API=y             #异步开启

#断言支持 调试状态下使用 控制台调试
CONFIG_ASSERT=y
# INF 级别
CONFIG_LOG_DEFAULT_LEVEL=3          
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_CONSOLE=y

#开启编码器
CONFIG_QDEC_STM32=y

#定时器
CONFIG_COUNTER=y
CONFIG_COUNTER_TIMER_STM32=y

# PWM 开启motor
CONFIG_PWM=y
CONFIG_GPIO=y


