CONFIG_GPIO=y
CONFIG_CONSOLE=y
CONFIG_SYS_CLOCK_EXISTS=y
CONFIG_DEBUG=y

#SSD1306

#enable I2c
CONFIG_I2C=y

#enable SSD1306 display
CONFIG_SSD1306=y

#enable display subsystem
CONFIG_DISPLAY=y




#如果使用lvgl
#CONFIG_LVGL=y

#按键 Input Subsystem(可选)

CONFIG_INPUT=y
CONFIG_INPUT_GPIO_KEYS=y

#shell(i2c scan调试)
CONFIG_SHELL=y
CONFIG_I2C_SHELL=y