
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/zephyr_default.cmake:133 (include)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:11 (find_package)"
    message: |
      The target system is: Generic - 4.4.99 - arm
      The host system is: Windows - 10.0.26200 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/zephyr_default.cmake:133 (include)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:11 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: D:/Downloads/setup/zephyr-sdk-1.0.1/gnu/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        D:/Downloads/zephyr_new/myapp/new/car_2026/cmake-build-debug-zephyr/CMakeFiles/3.31.6/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/zephyr_default.cmake:133 (include)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:11 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: D:/Downloads/setup/zephyr-sdk-1.0.1/gnu/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        D:/Downloads/zephyr_new/myapp/new/car_2026/cmake-build-debug-zephyr/CMakeFiles/3.31.6/CompilerIdCXX/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1237 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/kernel.cmake:135 (enable_language)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/zephyr_default.cmake:133 (include)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:11 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      arm-zephyr-eabi-gcc.exe (Zephyr SDK 1.0.1) 14.3.0
      Copyright (C) 2024 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CheckCCompilerFlag.cmake:56 (cmake_check_compiler_flag)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/extensions.cmake:2576 (check_c_compiler_flag)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/extensions.cmake:1246 (check_compiler_flag)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/extensions.cmake:2615 (zephyr_check_compiler_flag)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/extensions.cmake:2591 (target_cc_option_fallback)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules/extensions.cmake:156 (target_cc_option)"
      - "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/CMakeLists.txt:634 (zephyr_cc_option)"
    directories:
      source: "D:/Downloads/zephyr_new/myapp/new/car_2026/cmake-build-debug-zephyr/CMakeFiles/CMakeScratch/TryCompile-zads6w"
      binary: "D:/Downloads/zephyr_new/myapp/new/car_2026/cmake-build-debug-zephyr/CMakeFiles/CMakeScratch/TryCompile-zads6w"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "D:/Downloads/zephyr_new/zephyr_guanfang/zephyr/cmake/modules"
    buildResult:
      variable: "check_fmacro_prefix_map_D__Downloads_zephyr_new_myapp_new_car_2026_CMAKE_SOURCE_DIR_C__nostartfiles__nostdlib__isystem__D__Downloads_setup_zephyr_sdk_1_0_1_gnu_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_14_3_0_include___isystem__D__Downloads_setup_zephyr_sdk_1_0_1_gnu_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_14_3_0_include___Wl___unresolved_symbols_ignore_in_object_files__Wl___entry_0__fuse_ld_bfd"
      cached: true
      stdout: |
        Change Dir: 'D:/Downloads/zephyr_new/myapp/new/car_2026/cmake-build-debug-zephyr/CMakeFiles/CMakeScratch/TryCompile-zads6w'
        
        Run Build Command(s): D:/Downloads/app/Scripts/ninja.exe -v cmTC_89d15
        [1/2] D:\\Downloads\\setup\\zephyr-sdk-1.0.1\\gnu\\arm-zephyr-eabi\\bin\\arm-zephyr-eabi-gcc.exe -Dcheck_fmacro_prefix_map_D__Downloads_zephyr_new_myapp_new_car_2026_CMAKE_SOURCE_DIR_C__nostartfiles__nostdlib__isystem__D__Downloads_setup_zephyr_sdk_1_0_1_gnu_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_14_3_0_include___isystem__D__Downloads_setup_zephyr_sdk_1_0_1_gnu_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_14_3_0_include___Wl___unresolved_symbols_ignore_in_object_files__Wl___entry_0__fuse_ld_bfd  -nostartfiles -nostdlib -isystem "D:/Downloads/setup/zephyr-sdk-1.0.1/gnu/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/14.3.0/include" -isystem "D:/Downloads/setup/zephyr-sdk-1.0.1/gnu/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/14.3.0/include" -Wl,--unresolved-symbols=ignore-in-object-files -Wl,--entry=0 -fuse-ld=bfd   -fmacro-prefix-map=D:/Downloads/zephyr_new/myapp/new/car_2026=CMAKE_SOURCE_DIR -o CMakeFiles/cmTC_89d15.dir/src.c.obj -c D:/Downloads/zephyr_new/myapp/new/car_2026/cmake-build-debug-zephyr/CMakeFiles/CMakeScratch/TryCompile-zads6w/src.c
        [2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && D:\\Downloads\\setup\\zephyr-sdk-1.0.1\\gnu\\arm-zephyr-eabi\\bin\\arm-zephyr-eabi-gcc.exe -nostartfiles -nostdlib -isystem "D:/Downloads/setup/zephyr-sdk-1.0.1/gnu/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/14.3.0/include" -isystem "D:/Downloads/setup/zephyr-sdk-1.0.1/gnu/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/14.3.0/include" -Wl,--unresolved-symbols=ignore-in-object-files -Wl,--entry=0 -fuse-ld=bfd  CMakeFiles/cmTC_89d15.dir/src.c.obj -o cmTC_89d15   && cd ."
        Active code page: 65001
        
      exitCode: 0
...
